//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db_lab_movies
{
    using System;
    using System.Collections.Generic;
    
    public partial class movies_info
    {
        public int movie_id { get; set; }
        public string title { get; set; }
        public string Director_Name { get; set; }
        public string Production_Company { get; set; }
        public string release_date { get; set; }
        public Nullable<long> budget { get; set; }
        public Nullable<int> runtime { get; set; }
        public string Movie_Genere { get; set; }
        public string Movie_Original_Language { get; set; }
    }
}
