//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db_lab_movies
{
    using System;
    using System.Collections.Generic;
    
    public partial class persons_info
    {
        public int person_id { get; set; }
        public string person_name { get; set; }
    }
}
